# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/bytedance/c/unix_socket_ww

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/bytedance/c/unix_socket_ww

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bytedance/c/unix_socket_ww/CMakeFiles /Users/bytedance/c/unix_socket_ww/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bytedance/c/unix_socket_ww/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named select_server

# Build rule for target.
select_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 select_server
.PHONY : select_server

# fast build rule for target.
select_server/fast:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/build
.PHONY : select_server/fast

0.hello_socket/client.o: 0.hello_socket/client.c.o

.PHONY : 0.hello_socket/client.o

# target to build an object file
0.hello_socket/client.c.o:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/0.hello_socket/client.c.o
.PHONY : 0.hello_socket/client.c.o

0.hello_socket/client.i: 0.hello_socket/client.c.i

.PHONY : 0.hello_socket/client.i

# target to preprocess a source file
0.hello_socket/client.c.i:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/0.hello_socket/client.c.i
.PHONY : 0.hello_socket/client.c.i

0.hello_socket/client.s: 0.hello_socket/client.c.s

.PHONY : 0.hello_socket/client.s

# target to generate assembly for a file
0.hello_socket/client.c.s:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/0.hello_socket/client.c.s
.PHONY : 0.hello_socket/client.c.s

0.hello_socket/server.o: 0.hello_socket/server.c.o

.PHONY : 0.hello_socket/server.o

# target to build an object file
0.hello_socket/server.c.o:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/0.hello_socket/server.c.o
.PHONY : 0.hello_socket/server.c.o

0.hello_socket/server.i: 0.hello_socket/server.c.i

.PHONY : 0.hello_socket/server.i

# target to preprocess a source file
0.hello_socket/server.c.i:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/0.hello_socket/server.c.i
.PHONY : 0.hello_socket/server.c.i

0.hello_socket/server.s: 0.hello_socket/server.c.s

.PHONY : 0.hello_socket/server.s

# target to generate assembly for a file
0.hello_socket/server.c.s:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/0.hello_socket/server.c.s
.PHONY : 0.hello_socket/server.c.s

1.time_server/client.o: 1.time_server/client.c.o

.PHONY : 1.time_server/client.o

# target to build an object file
1.time_server/client.c.o:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/1.time_server/client.c.o
.PHONY : 1.time_server/client.c.o

1.time_server/client.i: 1.time_server/client.c.i

.PHONY : 1.time_server/client.i

# target to preprocess a source file
1.time_server/client.c.i:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/1.time_server/client.c.i
.PHONY : 1.time_server/client.c.i

1.time_server/client.s: 1.time_server/client.c.s

.PHONY : 1.time_server/client.s

# target to generate assembly for a file
1.time_server/client.c.s:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/1.time_server/client.c.s
.PHONY : 1.time_server/client.c.s

2.echo/v1/client.o: 2.echo/v1/client.c.o

.PHONY : 2.echo/v1/client.o

# target to build an object file
2.echo/v1/client.c.o:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/2.echo/v1/client.c.o
.PHONY : 2.echo/v1/client.c.o

2.echo/v1/client.i: 2.echo/v1/client.c.i

.PHONY : 2.echo/v1/client.i

# target to preprocess a source file
2.echo/v1/client.c.i:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/2.echo/v1/client.c.i
.PHONY : 2.echo/v1/client.c.i

2.echo/v1/client.s: 2.echo/v1/client.c.s

.PHONY : 2.echo/v1/client.s

# target to generate assembly for a file
2.echo/v1/client.c.s:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/2.echo/v1/client.c.s
.PHONY : 2.echo/v1/client.c.s

2.echo/v2/server.o: 2.echo/v2/server.c.o

.PHONY : 2.echo/v2/server.o

# target to build an object file
2.echo/v2/server.c.o:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/2.echo/v2/server.c.o
.PHONY : 2.echo/v2/server.c.o

2.echo/v2/server.i: 2.echo/v2/server.c.i

.PHONY : 2.echo/v2/server.i

# target to preprocess a source file
2.echo/v2/server.c.i:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/2.echo/v2/server.c.i
.PHONY : 2.echo/v2/server.c.i

2.echo/v2/server.s: 2.echo/v2/server.c.s

.PHONY : 2.echo/v2/server.s

# target to generate assembly for a file
2.echo/v2/server.c.s:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/2.echo/v2/server.c.s
.PHONY : 2.echo/v2/server.c.s

3.multiple_io/poll/poll_cli.o: 3.multiple_io/poll/poll_cli.c.o

.PHONY : 3.multiple_io/poll/poll_cli.o

# target to build an object file
3.multiple_io/poll/poll_cli.c.o:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/3.multiple_io/poll/poll_cli.c.o
.PHONY : 3.multiple_io/poll/poll_cli.c.o

3.multiple_io/poll/poll_cli.i: 3.multiple_io/poll/poll_cli.c.i

.PHONY : 3.multiple_io/poll/poll_cli.i

# target to preprocess a source file
3.multiple_io/poll/poll_cli.c.i:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/3.multiple_io/poll/poll_cli.c.i
.PHONY : 3.multiple_io/poll/poll_cli.c.i

3.multiple_io/poll/poll_cli.s: 3.multiple_io/poll/poll_cli.c.s

.PHONY : 3.multiple_io/poll/poll_cli.s

# target to generate assembly for a file
3.multiple_io/poll/poll_cli.c.s:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/3.multiple_io/poll/poll_cli.c.s
.PHONY : 3.multiple_io/poll/poll_cli.c.s

3.multiple_io/poll/poll_server.o: 3.multiple_io/poll/poll_server.c.o

.PHONY : 3.multiple_io/poll/poll_server.o

# target to build an object file
3.multiple_io/poll/poll_server.c.o:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/3.multiple_io/poll/poll_server.c.o
.PHONY : 3.multiple_io/poll/poll_server.c.o

3.multiple_io/poll/poll_server.i: 3.multiple_io/poll/poll_server.c.i

.PHONY : 3.multiple_io/poll/poll_server.i

# target to preprocess a source file
3.multiple_io/poll/poll_server.c.i:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/3.multiple_io/poll/poll_server.c.i
.PHONY : 3.multiple_io/poll/poll_server.c.i

3.multiple_io/poll/poll_server.s: 3.multiple_io/poll/poll_server.c.s

.PHONY : 3.multiple_io/poll/poll_server.s

# target to generate assembly for a file
3.multiple_io/poll/poll_server.c.s:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/3.multiple_io/poll/poll_server.c.s
.PHONY : 3.multiple_io/poll/poll_server.c.s

3.multiple_io/select/select_cli.o: 3.multiple_io/select/select_cli.c.o

.PHONY : 3.multiple_io/select/select_cli.o

# target to build an object file
3.multiple_io/select/select_cli.c.o:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/3.multiple_io/select/select_cli.c.o
.PHONY : 3.multiple_io/select/select_cli.c.o

3.multiple_io/select/select_cli.i: 3.multiple_io/select/select_cli.c.i

.PHONY : 3.multiple_io/select/select_cli.i

# target to preprocess a source file
3.multiple_io/select/select_cli.c.i:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/3.multiple_io/select/select_cli.c.i
.PHONY : 3.multiple_io/select/select_cli.c.i

3.multiple_io/select/select_cli.s: 3.multiple_io/select/select_cli.c.s

.PHONY : 3.multiple_io/select/select_cli.s

# target to generate assembly for a file
3.multiple_io/select/select_cli.c.s:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/3.multiple_io/select/select_cli.c.s
.PHONY : 3.multiple_io/select/select_cli.c.s

3.multiple_io/select/select_ser.o: 3.multiple_io/select/select_ser.c.o

.PHONY : 3.multiple_io/select/select_ser.o

# target to build an object file
3.multiple_io/select/select_ser.c.o:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/3.multiple_io/select/select_ser.c.o
.PHONY : 3.multiple_io/select/select_ser.c.o

3.multiple_io/select/select_ser.i: 3.multiple_io/select/select_ser.c.i

.PHONY : 3.multiple_io/select/select_ser.i

# target to preprocess a source file
3.multiple_io/select/select_ser.c.i:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/3.multiple_io/select/select_ser.c.i
.PHONY : 3.multiple_io/select/select_ser.c.i

3.multiple_io/select/select_ser.s: 3.multiple_io/select/select_ser.c.s

.PHONY : 3.multiple_io/select/select_ser.s

# target to generate assembly for a file
3.multiple_io/select/select_ser.c.s:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/3.multiple_io/select/select_ser.c.s
.PHONY : 3.multiple_io/select/select_ser.c.s

common/common.o: common/common.c.o

.PHONY : common/common.o

# target to build an object file
common/common.c.o:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/common/common.c.o
.PHONY : common/common.c.o

common/common.i: common/common.c.i

.PHONY : common/common.i

# target to preprocess a source file
common/common.c.i:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/common/common.c.i
.PHONY : common/common.c.i

common/common.s: common/common.c.s

.PHONY : common/common.s

# target to generate assembly for a file
common/common.c.s:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/common/common.c.s
.PHONY : common/common.c.s

helper/helper.o: helper/helper.c.o

.PHONY : helper/helper.o

# target to build an object file
helper/helper.c.o:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/helper/helper.c.o
.PHONY : helper/helper.c.o

helper/helper.i: helper/helper.c.i

.PHONY : helper/helper.i

# target to preprocess a source file
helper/helper.c.i:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/helper/helper.c.i
.PHONY : helper/helper.c.i

helper/helper.s: helper/helper.c.s

.PHONY : helper/helper.s

# target to generate assembly for a file
helper/helper.c.s:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/helper/helper.c.s
.PHONY : helper/helper.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/main.c.s
.PHONY : main.c.s

types/types.o: types/types.c.o

.PHONY : types/types.o

# target to build an object file
types/types.c.o:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/types/types.c.o
.PHONY : types/types.c.o

types/types.i: types/types.c.i

.PHONY : types/types.i

# target to preprocess a source file
types/types.c.i:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/types/types.c.i
.PHONY : types/types.c.i

types/types.s: types/types.c.s

.PHONY : types/types.s

# target to generate assembly for a file
types/types.c.s:
	$(MAKE) -f CMakeFiles/select_server.dir/build.make CMakeFiles/select_server.dir/types/types.c.s
.PHONY : types/types.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... select_server"
	@echo "... 0.hello_socket/client.o"
	@echo "... 0.hello_socket/client.i"
	@echo "... 0.hello_socket/client.s"
	@echo "... 0.hello_socket/server.o"
	@echo "... 0.hello_socket/server.i"
	@echo "... 0.hello_socket/server.s"
	@echo "... 1.time_server/client.o"
	@echo "... 1.time_server/client.i"
	@echo "... 1.time_server/client.s"
	@echo "... 2.echo/v1/client.o"
	@echo "... 2.echo/v1/client.i"
	@echo "... 2.echo/v1/client.s"
	@echo "... 2.echo/v2/server.o"
	@echo "... 2.echo/v2/server.i"
	@echo "... 2.echo/v2/server.s"
	@echo "... 3.multiple_io/poll/poll_cli.o"
	@echo "... 3.multiple_io/poll/poll_cli.i"
	@echo "... 3.multiple_io/poll/poll_cli.s"
	@echo "... 3.multiple_io/poll/poll_server.o"
	@echo "... 3.multiple_io/poll/poll_server.i"
	@echo "... 3.multiple_io/poll/poll_server.s"
	@echo "... 3.multiple_io/select/select_cli.o"
	@echo "... 3.multiple_io/select/select_cli.i"
	@echo "... 3.multiple_io/select/select_cli.s"
	@echo "... 3.multiple_io/select/select_ser.o"
	@echo "... 3.multiple_io/select/select_ser.i"
	@echo "... 3.multiple_io/select/select_ser.s"
	@echo "... common/common.o"
	@echo "... common/common.i"
	@echo "... common/common.s"
	@echo "... helper/helper.o"
	@echo "... helper/helper.i"
	@echo "... helper/helper.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... types/types.o"
	@echo "... types/types.i"
	@echo "... types/types.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

